### PR TITLE
Replace Google Fonts with local hosting

### PR DESCRIPTION
**Pull request by quassy**
Just an idea for a quick fix to make the anti-Google crowd happy ;)

Get https://github.com/chrisrhymes/bulma-clean-theme/blob/master/_sass/_main.scss from the theme into c4ms repo and replace Google Fonts link with local fonts.

Preview here https://c4m.netlify.app/

### CODE REVIEW

**Comment by chk1** [comment]
You should probably add a reference to the original author and license somewhere, maybe inside the scss file or in the assets folder

**Comment by ubergesundheit** [comment]
> You should probably add a reference to the original author and license somewhere, maybe inside the scss file or in the assets folder

This :)

**Comment by quassy** [comment]
[Some things were better in the old days](https://en.wikipedia.org/wiki/Software_copyright#East_Germany) :D , but true and only fair!

**Comment by quassy** [comment]
One month later... like this? :)

**Review by ubergesundheit — APPROVED** [review]
:+1: Nice!

Feel free to merge

**Pull request merged**
